ProjectRequest/Controllers/TimeSheetController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ProjectRequest.Models;
using System.Text.RegularExpressions;

namespace ProjectRequest.Controllers
{
    public class TimeSheetController : Controller
    {
        //
        // GET: /TimeSheet/
        

        public ActionResult Index()
        {
            ProjectRequestEntities request = new ProjectRequestEntities();

            string name = Convert.ToString(User.Identity.Name);
            name = name.Remove(0, 8).ToLower();
            int sheetsNeeded;
            DateTime sheetDate;
            IEnumerable<TimeSheet> timeSheet = request.TimeSheets.Where(t => t.staffID == name && t.completed == false).OrderByDescending(t => t.sheetDate);

            TimeSheet currentSheet;

            var allSheets = request.TimeSheets.Where(t => t.staffID == name).OrderByDescending(t => t.sheetDate);
            if (allSheets == null || allSheets.Count() < 1)
            {
                TimeSheet mySheet = new TimeSheet();

                mySheet.sheetDate = DateTime.Today;
                mySheet.staffID = name;
                mySheet.completed = false;

                request.AddToTimeSheets(mySheet);
                request.SaveChanges();
            }

            currentSheet = allSheets.FirstOrDefault();

            //if (timeSheet == null || timeSheet.Count() < 1)
            //{
            //    var sheetsCompleted = request.TimeSheets.Where(t => t.staffID == name && t.completed == true).OrderByDescending(t => t.sheetDate);

            //    if (sheetsCompleted == null || sheetsCompleted.Count() < 1)
            //    {
            //        var todaySheet = request.TimeSheets.FirstOrDefault(t => t.sheetDate == DateTime.Today && t.completed == true);

            //        if (todaySheet == null)
            //        {
            //            TimeSheet mySheet = new TimeSheet();

            //            mySheet.sheetDate = DateTime.Today;
            //            mySheet.staffID = name;
            //            mySheet.completed = false;

            //            request.AddToTimeSheets(mySheet);
            //            request.SaveChanges();

            //            currentSheet = mySheet;
            //        }
            //        else
            //            currentSheet = todaySheet;
            //    }
            //    else
            //    {
            //        var lastSheetCompleted = sheetsCompleted.FirstOrDefault();

            //        currentSheet = lastSheetCompleted;
            //    }
                    
            //}

            //else
            //{
            //    currentSheet = timeSheet.FirstOrDefault(t => t.staffID == name);
            //}

            sheetDate = currentSheet.sheetDate.GetValueOrDefault();

            sheetDate = sheetDate.AddDays(1);

            sheetsNeeded = (int)DateTime.Today.Subtract(sheetDate).TotalDays;

            for (var startDate = 1; startDate <= sheetsNeeded + 1; startDate++)
            {
                if (sheetDate.DayOfWeek != DayOfWeek.Saturday && sheetDate.DayOfWeek != DayOfWeek.Sunday)
                {
                    var sheet = request.TimeSheets.FirstOrDefault(t => t.sheetDate == sheetDate && t.staffID == name);

                    if (sheet == null)
                    {
                        TimeSheet mySheet = new TimeSheet();

                        mySheet.sheetDate = sheetDate;
                        mySheet.staffID = name;
                        mySheet.completed = false;

                        request.AddToTimeSheets(mySheet);
                        request.SaveChanges();

                        sheetDate = sheetDate.AddDays(1);
                    }
                    else
                    {
                        sheetDate = sheetDate.AddDays(1);
                    }

                }
                else
                    sheetDate = sheetDate.AddDays(1);
            }

            IEnumerable<TimeSheet> lateSheets = request.TimeSheets.Where(t => t.staffID == name && t.completed == false).OrderByDescending(t => t.sheetDate);

            return View(lateSheets);
        }

        public ActionResult CreateTimeSheet(string startDate, string endDate, string assignedProjects = "true", string completed = "false")
        {
            ProjectRequestEntities request = new ProjectRequestEntities();

            int sheetID = Convert.ToInt32(Request.QueryString["sheetID"]);

            string name = Convert.ToString(User.Identity.Name);
            name = name.Remove(0, 8).ToLower();

            IEnumerable<Chore> chores = request.Chores.Where(c => c.sheetID == sheetID);

            IEnumerable<Request> requests = request.Requests;

            IEnumerable<Location> locations = request.Locations.OrderBy(l => l.name);

            TimeSheet timeSheet = request.TimeSheets.FirstOrDefault(t => t.sheetID == sheetID);

            Regex reg = new Regex(@"^(0[1-9]|1[012])[- /.](0[1-9]|[12][0-9]|3[01])[- /.](19|20)\d\d$");

            if (startDate != null && reg.IsMatch(startDate))
            {
                try
                {
                    requests = requests.Where(i => i.dateRequested >= Convert.ToDateTime(startDate));
                }
                catch { }
            }

            if (endDate != null && reg.IsMatch(endDate))
            {
                try
                {
                    requests = requests.Where(i => i.dateRequested < Convert.ToDateTime(endDate).AddDays(1));
                }
                catch { }
            }

            if (completed == "false")
                requests = requests.Where(i => i.completed == false);

            if (assignedProjects == "true")
            {
                var assignments = request.RequestAssignments.Where(r => r.staffID == name).Select(r => r.requestID).ToList();
                requests = requests.Where(r => assignments.Contains(r.reuqestID));
            }

            TimeSheetInfo sheetInfo = new TimeSheetInfo
            {
                requests = requests,
                chores = chores,
                locations = locations,
                timeSheet = timeSheet,
                startDate = startDate,
                endDate = endDate,
                completedProjects = completed,
                assignedProjects = assignedProjects
            };

            return View(sheetInfo);
        }

        public ActionResult EditTimeSheet(int sheetID, string startDate, string endDate, string assignedProjects = "true", string completed = "false")
        {
            ProjectRequestEntities request = new ProjectRequestEntities();

            //sheetID = Convert.ToInt32(Request.QueryString["sheetID"]);

            var chores = request.Chores.Where(c => c.sheetID == sheetID);
            var timeSheet = request.TimeSheets.FirstOrDefault(t => t.sheetID == sheetID);
            

            bool delete;
            bool complete;

            if (Request.Form["complete"] != null)
                complete = true;
            else
                complete = false;

            timeSheet.completed = complete;

            foreach (var chore in chores)
            {
                var currentRequest = request.Requests.FirstOrDefault(r => r.reuqestID == chore.requestID);

                if (Request.Form["Delete_" + chore.choreID] != null)
                    delete = true;
                else
                    delete = false;

                if (delete == false)
                {
                    chore.requestID = Convert.ToInt16(Request.Form["Request_" + chore.choreID]);
                    chore.chore1 = Request.Form["Chore_" + chore.choreID].ToString();
                    chore.timeSpent = Convert.ToDecimal(Request.Form["TimeSpent_" + chore.choreID]);
                    chore.name = currentRequest.projectName;
                }
                else
                {
                    request.DeleteObject(chore);
                }

            }

            request.SaveChanges();

            if (Request.Form["Request"] != null && Request.Form["Request"].ToString().Count() > 0)
            {
                int requestID = Convert.ToInt16(Request.Form["Request"]);

                var currentRequest = request.Requests.FirstOrDefault(r => r.reuqestID == requestID);

                Chore chore = new Chore();

                chore.sheetID = sheetID;
                chore.requestID = Convert.ToInt16(Request.Form["Request"]);
                chore.chore1 = Request.Form["Chore"].ToString();
                chore.timeSpent = Convert.ToDecimal(Request.Form["TimeSpent"]);
                chore.name = currentRequest.projectName;

                request.AddToChores(chore);
                request.SaveChanges();
            }

            return RedirectToAction("CreateTimeSheet", new { sheetID = sheetID, startDate = startDate, endDate = endDate, assignedProjects = assignedProjects, completed = completed });
        }

        public void LookUpSheet()
        {
            ProjectRequestEntities request = new ProjectRequestEntities();

            string name = Convert.ToString(User.Identity.Name);
            name = name.Remove(0, 8).ToLower();
            try
            {
                DateTime sheetDate = Convert.ToDateTime(Request.Form["sheetDate"]);

                var timeSheet = request.TimeSheets.FirstOrDefault(t => t.sheetDate == sheetDate && t.staffID == name);

                if (timeSheet != null)
                    Response.Redirect("~/TimeSheet/CreateTimeSheet?sheetID=" + timeSheet.sheetID.ToString());
                else
                    Response.Redirect("~/TimeSheet/Index?sheet=Fail");
            }

            catch
            {
                Response.Redirect("~/TimeSheet/Index?sheet=Fail");
            }


        }

        public string AddTime(string id, string description, string time)
        {

ProjectRequest/Views/TimeSheet/CreateTimeSheet.cshtml
@model ProjectRequest.Models.TimeSheetInfo

@{
    ViewBag.Title = "File CC Investigational Report";
    Layout = "~/Views/Shared/_Layout.cshtml";
    <link rel="stylesheet" href="~/css/magnific-popup.css"> 
    
    <style type="text/css">

        .white-popup {
  position: relative;
  background: #FFF;
  padding: 20px;
  width: auto;
  max-width: 700px;
  margin: 20px auto;
}

    </style>
}


<script type="text/javascript">
    $(document).ready(function () {
        var TotalTime = 0.00;
        var choreID;

        $('#dateStart').datepicker();
        $('#dateEnd').datepicker();
        $('textarea').trigger('autoresize');

        $('.timeSpent').each(function () {
            if ($.isNumeric($(this).val())) {
                TotalTime = TotalTime + parseFloat($(this).val());
            }
        });

        $("#totalTime").text(TotalTime);

        $(".timeSpent").change(function () {

            TotalTime = 0.00;

            $('.timeSpent').each(function () {
                if ($.isNumeric($(this).val())) {
                    TotalTime = TotalTime + parseFloat($(this).val());
                }
            });

            $("#totalTime").text(TotalTime);

        });


        $('.open-popup-link').magnificPopup({
            type: 'inline'
        }).click(function()
        {
            choreID = $(this).attr('id');
        });


        $("#projectList div").hide();

        $("#projectList a").click(function (e) {
            var location = $(this).attr('href');
            $(location).toggle();
            e.preventDefault();
        });

        $(".setID").click(function (e) {
            var projectID = $(this).attr('href');
            var projectName = $(this).attr('title');

            if (choreID == "0") {
                $("#Request").val(projectID);
                $("#name").text(projectName);
            }
            else {
                $("#Request_" + choreID).val(projectID);
                $("#name_" + choreID).text(projectName);
            }

            $.magnificPopup.close();
        });
    });
</script>

@using (Html.BeginForm("EditTimeSheet", "TimeSheet", new { sheetID = Convert.ToInt32(Request.QueryString["sheetID"]) }))
{
    
    <fieldset class="CaseFilter z-depth-1">

    <legend>Filter Reports</legend>

    <div class="row">
    
        <div class="input-field col s12 m6 l3" >
            @if(Model.startDate != null)
            {
                <input type="text" name="startDate" id="dateStart" value="@Model.startDate" />
            }
            else
            {
                <input type="text" ng-model="sheet.startDate" name="startDate" id="dateStart"  />
            }
            <label for="dateStart">Date Start:</label>
        </div>

        <div class="input-field col s12 m6 l3" >
            @if(Model.endDate != null)
            {
                <input type="text" name="endDate" id="dateEnd" value="@Model.endDate" />
            }
            else
            {
                <input type="text" ng-model="sheet.endDate" name="endDate" id="dateEnd" />
            }
            <label for="dateEnd">Date End:</label>
        </div>
        
        <div class="input-field col s12 m6 l3" >
            <select name="assignedProjects" id="assignedProjects">
                <option value="00">Please Select:</option>
                    @if (Model.assignedProjects == "false")
                    {
                        <option value="true">Yes</option>
                        <option value="false" selected="selected">No</option>
                    }

                    else
                    {
                        <option value="true" selected="selected">Yes</option>
                        <option value="false">No</option>
                    }
        
            </select>
            <label for="assignedProjects">My Cases Only:</label>
        </div>
        
        <div class="input-field col s12 m6 l3" >
            <select name="completed" id="completed">
                <option value="00">Please Select:</option>

                    @if (Model.completedProjects == "false")
                    {
                        <option value="true">Yes</option>
                        <option value="false" selected="selected">No</option>
                    }

                    else
                    {
                        <option value="true" selected="selected">Yes</option>
                        <option value="false">No</option>
                    }
         
            </select>
            <label for="completed">Show Completed Cases:</label>
        </div>
    
    </div>
    
    <button class="btn waves-effect waves-light button" type="submit" name="action">Filter Case Files
        <i class="material-icons right">search</i>
    </button>

</fieldset>    
 <br /><br />
    

<fieldset class="z-depth-1">
    <legend>CC Report</legend>

    <p id="reportTime"><b>Total Time: <span id="totalTime"></span></b></p>

    <div class='datagrid z-depth-1'>
        <table>
            <thead><tr><th>Select Case</th><th class="hide-on-med-and-down">ID</th><th>Name</th><th>Description</th><th>Hours</th><th class="hide-on-med-and-down">Delete</th></tr></thead>
            <tbody>

                @{
                    string rowColor = "alt";
                }

                @foreach (var chore in Model.chores)
                {
                    //var project = Model.requests.FirstOrDefault(r => r.reuqestID == chore.requestID);
                    //string name = "";


                    //if (project != null)
                    //{
                    //    name = project.projectName;
                    //}

                    if (rowColor == "noAlt")
                    {
                        rowColor = "alt";
                    }
                    else
                    {
                        rowColor = "noAlt";
                    }

                    <tr class="@rowColor">
                        <td><a href="#projectList" class="open-popup-link" id="@chore.choreID">Show Projects</a></td>
                        <td class="hide-on-med-and-down">
                            <div class="input-field">
                                <input type="text" name="Request_@chore.choreID" id="Request_@chore.choreID" value="@chore.requestID" class="order" />
                            </div>
                        </td>
                        <td ><span id="name_@chore.choreID">@chore.name</span></td>
                        <td>
                            <div class="input-field">
                                <textarea class="materialize-textarea" cols="175" name="Chore_@chore.choreID" id="Chore_@chore.choreID" class="task">@chore.chore1</textarea>
                            </div>
                        </td>
                        <td>
                            <div class="input-field">
                                <input type="text" name="TimeSpent_@chore.choreID" id="TimeSpent_@chore.choreID" value="@chore.timeSpent" class="timeSpent" />
                            </div>
                        </td>
                        <td class="hide-on-med-and-down">
                            <div class="switch">
                            <label>
                                <input type="checkbox" id="Delete_@chore.choreID" name="Delete_@chore.choreID"  />
                                <span class="lever"></span>
                            </label>
                            </div>
                        </td>
                    </tr>
                }
                @if (rowColor == "noAlt")
                {
                    rowColor = "alt";
                }
                else
                {
                    rowColor = "noAlt";
                }
                <tr class="@rowColor">
                    <td>
                        <a href="#projectList" class="open-popup-link" id="0">Show Projects</a>
                    </td>
                    <td class="hide-on-med-and-down"> 
                        <div class="input-field">
                        <input type="text" name="Request" id="Request" class="order" />
                        </div>
                    </td>
                    <td >
                        <span id="name"></span>
                    </td>
                    <td>
                        <div class="input-field">
                        <textarea class="materialize-textarea" cols="175" name="Chore" id="Chore"></textarea>
                        </div>
                    </td>
                    <td>
                        <div class="input-field">
                            <input type="text" name="TimeSpent" id="TimeSpent"  />
                        </div>
                    </td>
                    <td></td>
                </tr>

            </tbody>

        </table>
    </div>
    <br />

    <div id="saveReport">
        @if (Model.timeSheet.completed == false)
        {
            <div class="switch">
                <label>
                    <input type="checkbox" name="complete" id="complete">
                    <span class="lever"></span>
                    Complete Report
                </label>
            </div>
        }
        else
        {
            <div class="switch">
                <label>
                    <input type="checkbox" checked name="complete" id="complete">
                    <span class="lever"></span>
                    Report is Complete
                </label>
            </div>
        }

        <br />

        <button class="btn waves-effect waves-light button" type="submit" name="action">Save Report
            <i class="material-icons right">library_books</i>
        </button>
    </div>
    </fieldset>                


    <div id="projectList" class="white-popup mfp-hide">
        @foreach (var location in Model.locations)
        {
            <p class="ViewHeader"><a href="#@location.locationID">@location.name</a></p>
            <div class='datagrid z-depth-1' id="@location.locationID">
                <table>
                    <thead><tr><th>Select Case</th><th>Case Name</th><th class="hide-on-med-and-down">Date Requested</th><th class="hide-on-med-and-down">Requester</th></tr></thead>
                    <tbody>

                        @{
            rowColor = "alt";

            var projects = Model.requests.Where(p => p.location == location.name).OrderBy(p => p.projectName);
                        }

                        @foreach (var project in projects)
                        {
                            if (rowColor == "noAlt")
                            {
                                rowColor = "alt";
                            }
                            else
                            {
                                rowColor = "noAlt";
                            }

                            <tr class="@rowColor">
                                <td><a href="@project.reuqestID" title="@project.projectName" class="setID">Select</a></td>
                                <td>@project.projectName</td>
                                <td class="hide-on-med-and-down">@project.dateRequested</td>
                                <td class="hide-on-med-and-down">@project.name</td>
                            </tr>

                        }

                    </tbody>

                </table>
            </div>
        }
    </div>
    <script src="~/js/jquery.magnific-popup.js"></script>
                            }

ProjectRequest/Views/TimeSheet/Index.cshtml
@model IEnumerable<ProjectRequest.Models.TimeSheet>

@{
    ViewBag.Title = "CC Investigational Reports";
    Layout = "~/Views/Shared/_LayoutCopy22017.cshtml";
}

<script type="text/javascript">
    $(document).ready(function () {
        $('#TimeSheet').submit(function (e) {

            e.preventDefault();

            if ($("#timeSheet").val() != "00") {
                document.TimeSheet.action = "/ProjectRequest/ProjectRequest/TimeSheet/CreateTimeSheet?sheetID=" + $("#timeSheet").val();

                document.TimeSheet.submit();
            }
            else {
                alert("Please select a report to view");
            }
        });
    });
</script>

@using (Html.BeginForm("CreateTimeSheet", "TimeSheet", FormMethod.Post, new { name = "TimeSheet", id = "TimeSheet" }))
{
    <fieldset class="CaseFilter z-depth-1">
    <legend>CC Reports</legend>


    <div class="row">
    <div class="input-field col s12 m6 l4" >
    <select id="timeSheet" name="timeSheet">
        <option value="00">Please Select:</option>
        @foreach(var sheet in Model)
        {
            DateTime date = sheet.sheetDate.GetValueOrDefault();
            <option value="@sheet.sheetID">@date.DayOfWeek.ToString() (@date.ToShortDateString())</option>
        }
    </select>
    <label>Select Report</label>
    </div>
    </div>

    
    <button class="btn waves-effect waves-light button" type="submit" name="action">File Report
        <i class="material-icons right">library_books</i>
    </button>

    </fieldset>
}
<br />

@using (Html.BeginForm("LookUpSheet", "TimeSheet", FormMethod.Post, new { name = "OldTimeSheet", id = "OldTimeSheet" }))
{
    
    <fieldset class="CaseFilter z-depth-1">
    <legend>Look Up CC Report</legend>


    @if(Request.QueryString["sheet"] == "Fail") 
    {
        <p><b>Could not find report with this date.</b></p>
    }
    
    <div class="row">
    <div class="input-field col s12 m6 l4" >
    <label>Look up by date:</label>
    <input type="text" name="sheetDate" class="datepicker" id="sheetDate" />
    </div>
    </div>

    
    <button class="btn waves-effect waves-light button" type="submit" name="action">Look Up Report
        <i class="material-icons right">event</i>
    </button>

    </fieldset>
}