ProjectRequest/Models/RequestInfo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ProjectRequest.Models
{
    public class RequestInfo
    {
        public RequestInfoViewModel GetRequestInfo(int requestID)
        {
            ProjectRequestEntities request = new ProjectRequestEntities();

            var answers = request.Answers.Where(a => a.requestID == requestID);
            IEnumerable<Models.Attachment> attachments = request.Attachments.Where(a => a.requestID == requestID);
            IEnumerable<Staff> staff = request.Staffs;
            IEnumerable<RequestAssignment> requestAssignment = request.RequestAssignments.Where(r => r.requestID == requestID);
            IEnumerable<TaskList> taskList = request.TaskLists.Where(r => r.requestID == requestID).OrderBy(t => t.orderNum);
            List<TaskAssignment> taskAssignment = new List<TaskAssignment>();
            List<AnswerListViewModel> myAnswerList = new List<AnswerListViewModel>();

            foreach (var task in taskList)
            {
                var currentTasks = request.TaskAssignments.Where(t => t.taskID == task.taskID);

                foreach (var item in currentTasks)
                {
                    taskAssignment.Add(item);
                }
                
            }

            foreach(var answer in answers)
            {
                var question = request.Questions.FirstOrDefault(q => q.questionID == answer.QuestionID);

                if (question != null)
                {
                    AnswerListViewModel list = new AnswerListViewModel
                    {
                        answer = answer,
                        question = question.Question1
                    };

                    myAnswerList.Add(list);
                }
            }

            var currentRequst = request.Requests.FirstOrDefault(r => r.reuqestID == requestID);
            var poNum = request.PONums.Where(r => r.requestID == requestID);

            RequestInfoViewModel requestList = new RequestInfoViewModel
            {
                answerList = myAnswerList,
                attachment = attachments,
                request = currentRequst,
                staff = staff,
                assignments = requestAssignment,
                category = request.Categories.FirstOrDefault(c => c.categoryID == currentRequst.categoryID),
                cateogires = request.Categories,
                location = request.Locations,
                taskList = taskList,
                taskStatus = request.TaskStatus1,
                templateList = request.Templates,
                taskAssignments = taskAssignment,
                poNum = poNum
            };

            return requestList;
        }

    }
}

ProjectRequest/Models/RequestInfoViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using ProjectRequest.Models;

namespace ProjectRequest.Models
{
    public class RequestInfoViewModel
    {
        public IEnumerable<AnswerListViewModel> answerList { get; set; } 
        public IEnumerable<SubRequestInfo> subRequests { get; set; }
        public IEnumerable<Attachment> attachment { get; set; }
        public Request request { get; set; } 
        public IEnumerable<RequestAssignment> assignments { get; set; }
        public IEnumerable<Staff> staff { get; set; }
        public Category category { get; set; }
        public IEnumerable<Category> cateogires { get; set; }
        public IEnumerable<Location> location { get; set; }
        public IEnumerable<ProjectStatus> projectStatus { get; set; }

        public IEnumerable<TaskList> taskList { get; set; }
        public IEnumerable<TaskStatus> taskStatus { get; set; }
        public IEnumerable<Template> templateList { get; set; }

        public IEnumerable<TaskAssignment> taskAssignments { get; set; }
        public IEnumerable<PONum> poNum { get; set; }

        public Vendor vendor { get; set; }

        public IEnumerable<Vendor> vendorList { get; set; }

        public IEnumerable<vendorContact> vendorContacts { get; set; }

    }


}

ProjectRequest/Controllers/AssignmentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ProjectRequest.Models;
using System.Text.RegularExpressions;
using System.Net.Mail;

namespace ProjectRequest.Controllers
{
    public class AssignmentController : Controller
    {
        ProjectRequestEntities request = new ProjectRequestEntities();
        public int PageSize = 100;


        [Authorize]
        public ViewResult Index(string dateStart, string dateEnd, string location, string category, int page = 1, string completed = "false")
        {
            IEnumerable<Request> info = request.Requests.OrderByDescending(i => i.dateRequested);
            PagingInfo pageInfo = new PagingInfo();
            IEnumerable<Models.Attachment> attachmnets = request.Attachments;

            Regex reg = new Regex(@"^(0[1-9]|1[012])[- /.](0[1-9]|[12][0-9]|3[01])[- /.](19|20)\d\d$");

           string name = Convert.ToString(User.Identity.Name);

            name = name.Remove(0, 8).ToLower();

           var requestAssignment = request.RequestAssignments.Where(r => r.staffID == name).Select(r => r.requestID).ToList();
 
           info = info.Where(a => requestAssignment.Contains(a.reuqestID));

            if (completed == "false")
                info = info.Where(i => i.completed == false);
            else if (completed == "true")
                info = info.Where(i => i.completed == true);


            if (location != "00" && location != null)
                info = info.Where(i => i.location == location);

            if (category != "00" && category != null)
                info = info.Where(i => i.categoryID == category);

            if (dateStart != null && dateEnd != null && reg.IsMatch(dateStart) && reg.IsMatch(dateEnd))
            {
                try
                {
                    info = info.Where(i => i.dateRequested >= Convert.ToDateTime(dateStart) && i.dateRequested <= Convert.ToDateTime(dateEnd));
                }
                catch { }
            }

            List<RequestListViewModel> requestList = new List<RequestListViewModel>();
            

            foreach (var item in info)
            {
                RequestListViewModel myList = new RequestListViewModel()
                {
                    Request = item,
                    Category = request.Categories.FirstOrDefault(c => c.categoryID == item.categoryID)
                };

                requestList.Add(myList);
            }

            int pageTotal = requestList.Count();

            RequestListCategory requestListCategory = new RequestListCategory
            {
                requestList = requestList.Skip((page - 1) * PageSize).Take(PageSize),
                cateogires = request.Categories,
                PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = PageSize,
                    TotalItems = pageTotal,
                    dateStart = dateStart,
                    dateEnd = dateEnd,
                    category = category,
                    completed = completed,
                    location = location,
                    completionStatus = pageInfo.PopulateStatus(),
                },
                location = request.Locations,
                attachments = attachmnets
            };

            ViewData["Categories"] = request.Categories;

            return View(requestListCategory);
        }

        public ViewResult RequestInfo(int requestID, string currentTrackID)
        {
            var answers = request.Answers.Where(a => a.requestID == requestID);
            IEnumerable<Models.Attachment> attachments = request.Attachments.Where(a => a.requestID == requestID);
            IEnumerable<Staff> staff = request.Staffs;
            IEnumerable<RequestAssignment> requestAssignment = request.RequestAssignments.Where(r => r.requestID == requestID);

            List<AnswerListViewModel> myAnswerList = new List<AnswerListViewModel>();


            foreach(var answer in answers)
            {
                var question = request.Questions.FirstOrDefault(q => q.questionID == answer.QuestionID);

                if (question != null)
                {
                    AnswerListViewModel list = new AnswerListViewModel
                    {
                        answer = answer,
                        question = question.Question1
                    };

                    myAnswerList.Add(list);
                }
            }

            var currentRequst = request.Requests.FirstOrDefault(r => r.reuqestID == requestID);

            RequestInfoViewModel requestList = new RequestInfoViewModel
            {
                answerList = myAnswerList,
                attachment = attachments,
                request = currentRequst,
                staff = staff,
                assignments = requestAssignment,
                category = request.Categories.FirstOrDefault(c => c.categoryID == currentRequst.categoryID),
                cateogires = request.Categories,
                location = request.Locations
            };

            return View(requestList);
        }

        [HttpPost]
        public ActionResult SearchCurrentTrack(string currentTrackID)
        {
            var currentTrackRequest = request.Requests.FirstOrDefault(c => c.currentTrackID == currentTrackID);

            if (currentTrackRequest != null)
                return RedirectToAction("RequestInfo", new { requestID = currentTrackRequest.reuqestID });
            else
                return View();
        }

        [HttpPost]
        public ActionResult EditRequest(FormCollection form)
        {
            int requestID = Convert.ToInt16(Request.QueryString["requestID"]);

            EditRequesterInfo(form);
            EditRequestContent(form);
            EditAssignment(form);

            return RedirectToAction("RequestInfo", new { requestID = requestID });
        }


        public void EditRequesterInfo(FormCollection form)
        {
            IEnumerable<Staff> staff = request.Staffs;

            string emailBody;
            MailMessage mail = new MailMessage();
            SmtpClient mailer = new SmtpClient("owa13.Sullivan.edu");
            //mail.Bcc.Add(new MailAddress("websupport@sullivan.edu"));
            //mail.Bcc.Add(new MailAddress("istarbuck@sullivan.edu"));

            mail.IsBodyHtml = true;
            mailer.EnableSsl = false;
            mail.From = new MailAddress("ProjectRequest@CC.com");


            int requestID = Convert.ToInt16(Request.QueryString["requestID"]);

            string currentTrackID = Request.Form["CT#"].ToString();
            string completed = Request.Form["completed"].ToString();

            Dictionary<string, bool> staffing = new Dictionary<string, bool>();

            var editRequest = request.Requests.FirstOrDefault(r => r.reuqestID == requestID);

            if (editRequest.currentTrackID == null && currentTrackID != null && currentTrackID.Length > 3)
            {
                //mail.To.Add("ekuhn@sullivan.edu");

                emailBody = "<p>Current Track ID assigned for " + editRequest.projectName + ". <a href='https://secure.sullivan.edu/ProjectRequest/ProjectRequest/Request/RequestInfo?requestID="
                    + requestID.ToString() + "'>Click Here</a> to view the project</p>";

                mail.Body = emailBody;
                mail.Subject = "Creative Communications Current Track ID Assigned";

                mailer.Send(mail);

                mail.To.Clear();
                try
                {
                    mail.To.Add(editRequest.email);

                    mail.Subject = "Creative Communications Projeject Request Received";

                    mail.Body = "Your request of '" + editRequest.projectName + "' has been received by Creative Communications. Project number " + currentTrackID + ".";
                    mailer.Send(mail);
                }
                catch { }

               
            }

            editRequest.currentTrackID = currentTrackID;

            if (completed == "Yes" && editRequest.completed == false)
            {
                editRequest.completed = true;

                mail.To.Clear();
                try
                {
                    mail.To.Add(editRequest.email);
                    mail.To.Add("istarbuck@sullivan.edu");

                    mail.Subject = "Creative Communications Project Request Completed";

                    mail.Body = "Your request of '" + editRequest.projectName + "' has been been completed. Project number " + currentTrackID + ".";
                    mailer.Send(mail);
                }
                catch { }
            }
            else if (completed == "No")
                editRequest.completed = false;

            editRequest.contactInfo = Request.Form["contactInfo"].ToString();
            editRequest.dateRequested = Convert.ToDateTime(Request.Form["date"]);
            editRequest.location = Request.Form["location"].ToString();
            editRequest.name = Request.Form["name"].ToString();
            editRequest.categoryID = Request.Form["category"].ToString();
            editRequest.doaName = Request.Form["doaName"].ToString();
            editRequest.projectName = Request.Form["projectName"].ToString();
            editRequest.email = Request.Form["email"].ToString();
            editRequest.additionalInfo = Request.Form["additionalInfo"].ToString();
            editRequest.comment = Request.Form["comments"].ToString();

            request.SaveChanges();
        }


        public void EditRequestContent(FormCollection form)
        {
            int requestID = Convert.ToInt16(Request.QueryString["requestID"]);

            var answers = request.Answers.Where(a => a.requestID == requestID);

            foreach (var answer in answers)
            {

ProjectRequest/Views/Assignment/Index.cshtml
@model ProjectRequest.Models.RequestListCategory
@using ProjectRequest.HTMLHelpers;

<script type="text/javascript">
    $(document).ready(function () {
        $('#dateStart').datepicker();
        $('#dateEnd').datepicker();
    });
</script>

<h3>Filter Requests</h3>

@using (Html.BeginForm("Index", "Assignment"))
{
    <label for="dateStart">Date Start:</label>
    if (Model.PagingInfo.dateStart != null)
    {
        <input type="text" name="dateStart" id="dateStart" value="@Model.PagingInfo.dateStart" />
    }
    else
    {
        <input type="text" name="dateStart" id="dateStart" />
    }
    <br />
    
    <label for="dateEnd">Date End:</label>
    if (Model.PagingInfo.dateEnd != null)
    {
        <input type="text" name="dateEnd" id="dateEnd" value="@Model.PagingInfo.dateEnd" />
    }
    else
    {
        <input type="text" name="dateEnd" id="dateEnd" />
    }
    <br />
    
    <label for="location">Location:</label>
    <select name="location" id="location">
        <option value="00">Please Select:</option>
        @foreach (var location in Model.location)
        {
            if (location.name == Model.PagingInfo.location)
            {
                <option value="@location.name" selected="selected">@location.name</option>      
            }   
            else
            {
                <option value="@location.name" >@location.name</option>
            }
        }
    </select>
    <br />
    
    <label for="category">Category:</label>
    <select name="category" id="category">
        <option value="00">Please Select:</option>
        @foreach (var category in Model.cateogires)
        {
            if (category.categoryID == Model.PagingInfo.category)
            {
                <option value="@category.categoryID" selected="selected">@category.categoryName</option>
            }

            else
            {
                <option value="@category.categoryID">@category.categoryName</option>
            }
        }
    </select>
    <br />

    <label for="completed">Completion Status:</label>
    <select name="completed" id="completed">
        <option value="00">Please Select:</option>
        @foreach (var status in Model.PagingInfo.completionStatus)
        {
            if (status.Key == Model.PagingInfo.completed)
            {
                <option value="@status.Key" selected="selected">@status.Value</option>
            }

            else
            {
                <option value="@status.Key">@status.Value</option>
            }
        }   
    </select>
    <br />
    
    <input type="submit" name="search" value="Filter Results" />
}

<h3>Project Requests</h3>

<div class='datagrid z-depth-1'>
<table>
<thead><tr><th>CT#</th><th>Date Submitted</th><th>Requester Name</th><th>Approved By</th><th>Project Name:</th><th>Details</th><th>Location</th><th>Category</th><th>Attachments</th></tr></thead>
<tbody>

@{
    string rowColor = "alt";
}

@foreach (var request in Model.requestList)
{
    var myAttachments = Model.attachments.Where(a => a.requestID == request.Request.reuqestID);
    
    if (rowColor == "noAlt")
    {
        rowColor = "alt";
    }
    else
    {
        rowColor = "noAlt";
    }
    
    <tr class="@rowColor">
    <td>@request.Request.currentTrackID</td>
    <td>@request.Request.dateRequested</td>
    <td>@request.Request.name</td>
    <td>@request.Request.doaName</td>
    <td>@request.Request.projectName</td>
    <td>@Html.ActionLink("View Request", "RequestInfo", new { requestID = @request.Request.reuqestID }, new { target = "_blank" }) </td>
    <td>@request.Request.location</td>
    <td>@request.Category.categoryName</td>
    <td>
    @foreach (var attachment in myAttachments)
    {
        <a href="~/Attachments/@attachment.filePath">@attachment.filePath<br /></a>
    }    
    </td>
    </tr>
}

</tbody>

<tfoot>
<tr><td colspan="9">
<div class="paging">
<ul>
@Html.PageLinks(Model.PagingInfo, x => Url.Action("Index", new {page = x}))
</ul>
</div>
</td></tr>
</tfoot>
</table>

</div>

ProjectRequest/Views/Assignment/RequestInfo.cshtml
@model ProjectRequest.Models.RequestInfoViewModel

@{
    //ViewBag.Title = "Request Info";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<script type="text/javascript">
    $(document).ready(function () {
        $('#date').datepicker();
    });
</script>
<h3>Requester Info</h3>

@using (Html.BeginForm("EditRequest", "Assignment", new { requestID = Convert.ToInt16(Request.QueryString["requestID"]) }))
{
    <label for="CT#">CT#</label>
    <input type="text" name="CT#" id="CT#" value="@Model.request.currentTrackID" />
    <br />
    
    <label for="date">Date Submitted:</label>
    <input type="text" name="date" id="date" value="@Model.request.dateRequested" />
    <br />
    
    <label for="name">Requester Name:</label>
    <input type="text" name="name" id="name" value="@Model.request.name" />
    <br />
    
    <label for="email">Email Address:</label>
    <input type="text" name="email" id="email" value="@Model.request.email" />
    <br />
    
    <label for="doaName">Approved By:</label>
    <input type="text" name="doaName" id="doaName" value="@Model.request.doaName" />
    <br />

    <label for="projectName">Project Name:</label>
    <input type="text" name="projectName" id="projectName" value="@Model.request.projectName" />
    <br />
    
    <label for="contactInfo">Contact Info:</label>
    <input type="text" name="contactInfo" id="contactInfo" value="@Model.request.contactInfo" />
    <br />
    
    <label for="location">Location:</label>
    <select name="location" id="location">
        <option value="00">Please Select:</option>
        @foreach (var location in Model.location)
        {
            if (location.name == Model.request.location)
            {
                <option value="@location.name" selected="selected">@location.name</option>      
            }
            else
            {
                <option value="@location.name" >@location.name</option>
            }
        }
    </select>
    <br />
    
    <label for="category">Category:</label>
    <select name="category" id="category">
        <option value="00">Please Select:</option>
        @foreach (var category in Model.cateogires)
        {
            if (category.categoryID == Model.request.categoryID)
            {
                <option value="@category.categoryID" selected="selected">@category.categoryName</option>
            }

            else
            {
                <option value="@category.categoryID" disabled="disabled">@category.categoryName</option>
            }
        }
    </select>
    <br />
    
    <label for="comments">Comments:</label>
    <textarea cols="100" rows="1" id="comments" name="comments">@Model.request.comment</textarea>   
    <br />
    
    <label for="completed">Completed?</label>
    <select name="completed">
    @if (Model.request.completed == true)
    {
        <option value="Yes" selected="selected">Yes</option>
        <option value="No">No</option>
    }
    else
    {
        <option value="Yes" >Yes</option>
        <option value="No" selected="selected">No</option>
    }
    </select>
    <br />
    
    if (@Model.request.doaAttachment != "Submitted by DOA" && @Model.request.doaAttachment != "Approval not needed")
    {
        <h4><a href="~/Attachments/@Model.request.doaAttachment">Approval File</a></h4>
    }
    else
    {
        <h4>@Model.request.doaAttachment</h4>
    }
    
<h3>Request Info</h3>


    foreach (var request in Model.answerList)
    {
        <label for="@request.answer.AnswerID">@request.question</label>
        <textarea cols="100" rows="1" id="@request.answer.AnswerID" name="@request.answer.AnswerID">@request.answer.AnswerText</textarea>   
        <br />
    }
    
        <label for="additionalInfo">Additional Info</label>
        <textarea cols="100" rows="1" id="additionalInfo" name="additionalInfo">@Model.request.additionalInfo</textarea>   
        <br />

<h3>Attachments</h3>

<div class='datagrid z-depth-1'>
<table>

    <thead>
    <tr>
    <th>File Path</th>

    @if (Model.request.categoryID == "cool")
    {
        <th>Caption</th>
    }

    </tr>
    </thead>

@foreach (var attachment in Model.attachment)
{

    <tr>
    <td><a href="~/Attachments/@attachment.filePath">@attachment.filePath</a></td>
    @if (Model.request.categoryID == "cool")
    {
        <td>@attachment.caption</td>
    }
    </tr>
}


</table>
</div>


    <h3>Assign Request</h3>
var assignmentList = Model.assignments.Select(a => a.staffID).ToList();
foreach (var staff in Model.staff)
{
    if (assignmentList.Contains(staff.staffID))
    {
                    
                <p><input type="checkbox" id="CB_@staff.staffID" name="CB_@staff.staffID" value="@staff.staffID" checked="checked" /> @staff.firstName @staff.lastName</p>   
    }
    else
    {
                <p><input type="checkbox" id="CB_@staff.staffID" name="CB_@staff.staffID" value="@staff.staffID" /> @staff.firstName @staff.lastName</p> 
    }
}
        
    <input type="submit" name="assign" value="Submit Changes" />
        
}