ProjectRequest/Models/RequestInfo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ProjectRequest.Models
{
    public class RequestInfo
    {
        public RequestInfoViewModel GetRequestInfo(int requestID)
        {
            ProjectRequestEntities request = new ProjectRequestEntities();

            var answers = request.Answers.Where(a => a.requestID == requestID);
            IEnumerable<Models.Attachment> attachments = request.Attachments.Where(a => a.requestID == requestID);
            IEnumerable<Staff> staff = request.Staffs;
            IEnumerable<RequestAssignment> requestAssignment = request.RequestAssignments.Where(r => r.requestID == requestID);
            IEnumerable<TaskList> taskList = request.TaskLists.Where(r => r.requestID == requestID).OrderBy(t => t.orderNum);
            List<TaskAssignment> taskAssignment = new List<TaskAssignment>();
            List<AnswerListViewModel> myAnswerList = new List<AnswerListViewModel>();

            foreach (var task in taskList)
            {
                var currentTasks = request.TaskAssignments.Where(t => t.taskID == task.taskID);

                foreach (var item in currentTasks)
                {
                    taskAssignment.Add(item);
                }
                
            }

            foreach(var answer in answers)
            {
                var question = request.Questions.FirstOrDefault(q => q.questionID == answer.QuestionID);

                if (question != null)
                {
                    AnswerListViewModel list = new AnswerListViewModel
                    {
                        answer = answer,
                        question = question.Question1
                    };

                    myAnswerList.Add(list);
                }
            }

            var currentRequst = request.Requests.FirstOrDefault(r => r.reuqestID == requestID);
            var poNum = request.PONums.Where(r => r.requestID == requestID);

            RequestInfoViewModel requestList = new RequestInfoViewModel
            {
                answerList = myAnswerList,
                attachment = attachments,
                request = currentRequst,
                staff = staff,
                assignments = requestAssignment,
                category = request.Categories.FirstOrDefault(c => c.categoryID == currentRequst.categoryID),
                cateogires = request.Categories,
                location = request.Locations,
                taskList = taskList,
                taskStatus = request.TaskStatus1,
                templateList = request.Templates,
                taskAssignments = taskAssignment,
                poNum = poNum
            };

            return requestList;
        }

    }
}

ProjectRequest/Models/RequestInfoViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using ProjectRequest.Models;

namespace ProjectRequest.Models
{
    public class RequestInfoViewModel
    {
        public IEnumerable<AnswerListViewModel> answerList { get; set; } 
        public IEnumerable<SubRequestInfo> subRequests { get; set; }
        public IEnumerable<Attachment> attachment { get; set; }
        public Request request { get; set; } 
        public IEnumerable<RequestAssignment> assignments { get; set; }
        public IEnumerable<Staff> staff { get; set; }
        public Category category { get; set; }
        public IEnumerable<Category> cateogires { get; set; }
        public IEnumerable<Location> location { get; set; }
        public IEnumerable<ProjectStatus> projectStatus { get; set; }

        public IEnumerable<TaskList> taskList { get; set; }
        public IEnumerable<TaskStatus> taskStatus { get; set; }
        public IEnumerable<Template> templateList { get; set; }

        public IEnumerable<TaskAssignment> taskAssignments { get; set; }
        public IEnumerable<PONum> poNum { get; set; }

        public Vendor vendor { get; set; }

        public IEnumerable<Vendor> vendorList { get; set; }

        public IEnumerable<vendorContact> vendorContacts { get; set; }

    }


}

ProjectRequest/Controllers/RequestController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ProjectRequest.Models;
using System.Text.RegularExpressions;
using System.Net.Mail;
using System.IO;
using System.Web.Services;
using System.Web.Script.Services;
using System.Web.Script.Serialization;

namespace ProjectRequest.Controllers
{
    public class RequestController : Controller
    {
        //
        // GET: /Default/
        
        public int PageSize = 50;

        public ViewResult Index(string dateStart, string dateEnd, string location, string category, string excludeCategory, string search,
            string assignedTo, string projectStatus, string excludeStatus = "Denied", int page = 1, string completed = "false", string approvers = "No")
        {
            ProjectRequestEntities request = new ProjectRequestEntities();

            IEnumerable<Request> info = request.Requests.OrderByDescending(i => i.dateRequested).Where(r => r.categoryID != "timeSheet");
            PagingInfo pageInfo = new PagingInfo();
            IEnumerable<Models.Attachment> attachmnets = request.Attachments;
            var staffList = request.Staffs.Select(s => s.staffID).ToList();

            Regex reg = new Regex(@"^(0[1-9]|1[012])[- /.](0[1-9]|[12][0-9]|3[01])[- /.](19|20)\d\d$");

            string name = Convert.ToString(User.Identity.Name);

            name = name.Remove(0, 8).ToLower();

            if (search != null && search.Count() > 0)
            {
                info = request.Requests.OrderByDescending(i => i.dateRequested).Where(r => r.projectName.ToLower().Contains(search.ToLower()) 
                    || r.email.ToLower().Contains(search.ToLower()) || r.doaName.ToLower().Contains(search.ToLower())
                    || r.name.ToLower().Contains(search.ToLower()) || r.customID.Contains(search));

                if (reg.IsMatch(search))
                {
                    info = request.Requests.Where(r => r.dueDate == Convert.ToDateTime(search));
                }

                info = info.Where(r => r.categoryID != "timeSheet");
            }

            if(approvers == "Yes")
            {
                var approverList = request.Approvers.Select(a => a.sullivanID).ToList();

                if(approverList.Contains(name))
                {
                    var departments = request.Approvers.Where(s => s.sullivanID == name).Select(s => s.department).ToList();

                    if(departments.Count() == 1)
                    {
                        info = info.Where(i => i.department == departments[0] && i.status == "Pending");
                    }
                    else if(departments.Count() == 2)
                    {
                        info = info.Where(i => i.department == departments[0] || i.department == departments[1] && i.status == "Pending");
                    }
                }

            }

            if (staffList.Contains(name))
            {
                ViewBag.Role = "Agent";
            }
            else if (approvers.Contains(name))
            {
                ViewBag.Role = "Approver";
            }
            else
            {
                ViewBag.Role = "User";
            }

            if (completed == "false")
                info = info.Where(i => i.completed == false);
            else if (completed == "true")
                info = info.Where(i => i.completed == true);



            if (location != "00" && location != null)
                info = info.Where(i => i.location == location);

            if (category != "00" && category != null)
                info = info.Where(i => i.categoryID == category);

            if (excludeCategory != "00" && excludeCategory != null)
                info = info.Where(i => i.categoryID != excludeCategory);

            if (projectStatus != "00" && projectStatus != null)
                info = info.Where(i => i.status == projectStatus);

            if (excludeStatus != "00" && excludeStatus != null)
                info = info.Where(i => i.status != excludeStatus);

            if (dateStart != null && dateEnd != null && reg.IsMatch(dateStart) && reg.IsMatch(dateEnd))
            {
                try
                {
                    info = info.Where(i => i.dateRequested >= Convert.ToDateTime(dateStart) && i.dateRequested < Convert.ToDateTime(dateEnd).AddDays(1));
                }
                catch { }
            }

            if (assignedTo != "00" && assignedTo != null)
            {
                var requestAssignment = request.RequestAssignments.Where(r => r.staffID == assignedTo).Select(r => r.requestID).ToList();

                info = info.Where(a => requestAssignment.Contains(a.reuqestID));
            }

            List<RequestListViewModel> requestList = new List<RequestListViewModel>();
            

            foreach (var item in info)
            {
                RequestListViewModel myList = new RequestListViewModel()
                {
                    Request = item,
                    Category = request.Categories.FirstOrDefault(c => c.categoryID == item.categoryID)
                };

                requestList.Add(myList);
            }

            int pageTotal = requestList.Count();

            int subCases = Convert.ToInt16(requestList.Sum(r => r.Request.subProjects));

            ViewBag.CaseTotal = pageTotal;
            ViewBag.SubCases = subCases;

            RequestListCategory requestListCategory = new RequestListCategory
            {
                requestList = requestList.Skip((page - 1) * PageSize).Take(PageSize),
                cateogires = request.Categories.Where(c => c.version == "1"),
                PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = PageSize,
                    TotalItems = pageTotal,
                    dateStart = dateStart,
                    dateEnd = dateEnd,
                    category = category,
                    excludeCategory = excludeCategory,
                    completed = completed,
                    location = location,
                    completionStatus = pageInfo.PopulateStatus(),
                    search = search,
                    assignedTo = assignedTo,
                    projectStatus = projectStatus,
                    excludeStatus = excludeStatus
                },
                location = request.Locations,
                attachments = attachmnets,
                staffList = request.Staffs,
                projectStatus = request.ProjectStatus1.OrderBy(s => s.status)
            };

            ViewData["Categories"] = request.Categories;

            ViewBag.Method = "Index";

            return View(requestListCategory);
        }

        [AuthorizeUser]
        public ViewResult MyProjects(string dateStart, string dateEnd, string location, string category, string search, 
            string searchPO, string excludeCategory, string assignedTo, string projectStatus, string excludeStatus = "Denied", int page = 1, string completed = "false")
        {
            ProjectRequestEntities request = new ProjectRequestEntities();

            IEnumerable<Request> info = request.Requests.OrderByDescending(i => i.dateRequested).Where(r => r.categoryID != "timeSheet");
            PagingInfo pageInfo = new PagingInfo();
            IEnumerable<Models.Attachment> attachmnets = request.Attachments;
            var staffList = request.Staffs.Select(s => s.staffID).ToList();

            Regex reg = new Regex(@"^(0[1-9]|1[012])[- /.](0[1-9]|[12][0-9]|3[01])[- /.](19|20)\d\d$");

            if (search != null && search.Count() > 0)
            {
                info = request.Requests.OrderByDescending(i => i.dateRequested).Where(r => r.projectName.ToLower().Contains(search.ToLower())
                    || r.email.ToLower().Contains(search.ToLower()) || r.doaName.ToLower().Contains(search.ToLower())
                    || r.name.ToLower().Contains(search.ToLower()) || r.customID.Contains(search));

                if (reg.IsMatch(search))
                {
                    info = request.Requests.Where(r => r.dueDate == Convert.ToDateTime(search));
                }

                info = info.Where(r => r.categoryID != "timeSheet");
            }

            if (searchPO != null && searchPO.Count() > 0)
            {
                var poNum = request.PONums.Where(p => p.PONum1 == searchPO).Select(p => p.requestID).ToList();
                info = info.Where(p => poNum.Contains(p.reuqestID));
            }

            string name = Convert.ToString(User.Identity.Name);

            name = name.Remove(0, 8).ToLower();

            if (staffList.Contains(name))
            {
                ViewBag.Role = "Agent";
            }
            else
            {
                ViewBag.Role = "User";
            }

            if (assignedTo == "00" || assignedTo == null)
            {
                assignedTo = name;
            }

            var requestAssignment = request.RequestAssignments.Where(r => r.staffID == assignedTo).Select(r => r.requestID).ToList();

            info = info.Where(a => requestAssignment.Contains(a.reuqestID));

            if (completed == "false")
                info = info.Where(i => i.completed == false);
            else if (completed == "true")
                info = info.Where(i => i.completed == true);

            if (location != "00" && location != null)
                info = info.Where(i => i.location == location);

            if (category != "00" && category != null)
                info = info.Where(i => i.categoryID == category);

            if (excludeCategory != "00" && excludeCategory != null)
                info = info.Where(i => i.categoryID != excludeCategory);

            if (projectStatus != "00" && projectStatus != null)
                info = info.Where(i => i.status == projectStatus);

ProjectRequest/Views/Request/Index.cshtml
@model ProjectRequest.Models.RequestListCategory
@using ProjectRequest.HTMLHelpers;

@{
    ViewBag.Title = "All CC Cases";
    Layout = "~/Views/Shared/_LayoutCopy2017.cshtml";
    <link rel="stylesheet" href="~/css/print.css"> 
}

<script type="text/javascript">
    $(document).ready(function () {

    });
</script>

@Html.Partial("~/Views/Shared/ProjectList.cshtml", Model)

ProjectRequest/Views/Request/MyProjects.cshtml
@model ProjectRequest.Models.RequestListCategory

@{
    ViewBag.Title = "My CC Cases";
    Layout = "~/Views/Shared/_LayoutCopy2017.cshtml";
    <link rel="stylesheet" href="~/css/print.css"> 
}

@Html.Partial("~/Views/Shared/ProjectList.cshtml", Model)


@* <div ng-app="CCFilesApp" >

    <ul>
        <li><a href="#/routeOne">Route One</a></li>
        <li><a href="#/routeTwo">Route Two</a></li>
        <li><a href="#/routeThree">Route Three</a></li>
    </ul>

    <div ng-view></div>
</div>

<script>
    var CCFilesApp = angular.module('CCFilesApp', ['ngRoute']);

    var configFunction = function ($routeProvider) {
        $routeProvider.
            when('/routeOne', {
                templateUrl: '/ProjectRequest/ProjectRequest/Test/One'
            })
            .when('/routeTwo', {
                templateUrl: '/ProjectRequest/ProjectRequest/Test/Two'
            })
            .when('/routeThree', {
                templateUrl: '/ProjectRequest/ProjectRequest/Test/Three'
            });
    }
    configFunction.$inject = ['$routeProvider'];

    CCFilesApp.config(configFunction);

</script> *@

ProjectRequest/Views/Request/One.cshtml
<p>Test One</p>

ProjectRequest/Views/Request/PrintCase.cshtml
@model ProjectRequest.Models.Request

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Print Case</title>
</head>
<body>
    <div>
        
        <p><b>CC ID:</b> @Model.reuqestID</p>

        <p><b>Case Name:</b> @Model.projectName</p>

        <p><b>Location:</b> @Model.location</p>

        <p><b>Date Requested:</b> @Model.dateRequested</p>

        <p><b>Vendor:</b> @Model.vendor</p>

        <p><b>Ship To:</b> @Model.shipTo</p>

        <p><b>Subtotal:</b> @Model.subtotal</p>

        <p><b>Tax:</b> @Model.tax</p>

        <p><b>Total:</b> @Model.total</p>

        <p><b>Quantity:</b> @Model.Quantity</p>

        <p><b>Printer Specifications:</b> @Model.printerSpecifications</p>


    </div>
</body>
</html>

ProjectRequest/Views/Request/PrintMyProjects.cshtml
@model ProjectRequest.Models.RequestListCategory
@using ProjectRequest.HTMLHelpers

@{
    ViewBag.Title = "Print My Cases";
    Layout = null;
    
        <link href='https://fonts.googleapis.com/css?family=Roboto' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=PT+Sans' rel='stylesheet' type='text/css'>
    
    <style>
    table {

	    font-size:11px;
	    color:#333333;
	    border-width: 1px;
	    border-color: #666666;
	    border-collapse: collapse;
        font-size: 13px;
        font-family: 'Roboto', sans-serif;
    }
    table th {
	    border-width: 1px;
	    padding: 8px;
	    border-style: solid;
	    border-color: #666666;
	    background-color: #dedede;
    }
    table td {
	    border-width: 1px;
	    padding: 8px;
	    border-style: solid;
	    border-color: #666666;
	    background-color: #ffffff;
    }
 </style>
}


<div class='datagrid'>
<table>
<thead><tr><th>Due Date</th><th>Case Name:</th><th>Category</th></tr></thead>
<tbody>

@{
    string rowColor = "odd";
}

@foreach (var request in Model.requestList)
{
    var myAttachments = Model.attachments.Where(a => a.requestID == request.Request.reuqestID);

    if (rowColor == "odd")
    {
        rowColor = "even";
    }
    else
    {
        rowColor = "odd";
    }
    
    <tr class="@rowColor">
@*    <td class="noPrint hide-on-med-and-down mdl-layout--large-screen-only">@request.Request.currentTrackID</td>
    <td class="hide-on-med-and-down mdl-layout--large-screen-only">@request.Request.customID</td>
    <td class="hide-on-med-and-down mdl-layout--large-screen-only">@request.Request.dateRequested.ToShortDateString()</td>*@
@*    <td >@request.Request.name</td>*@
    <td >@request.Request.dueDate</td>
    <td>@request.Request.projectName</td>
@*    <td class="noPrint hide-on-med-and-down mdl-layout--large-screen-only">@Html.ActionLink("Edit Case", "RequestInfo", new { requestID = @request.Request.reuqestID }, new { target = "_blank" }) </td>
    <td class="hide-on-med-and-down mdl-layout--large-screen-only">@request.Request.location</td>*@
    <td class="hide-on-med-and-down mdl-layout--large-screen-only">@request.Category.categoryName</td>

@*    @foreach (var attachment in myAttachments)
    {
        <a href="~/Attachments/@attachment.filePath" target="_blank">@attachment.filePath<br /></a>
    }    
    </td>*@
    </tr>
}

</tbody>


</table>

</div>

ProjectRequest/Views/Request/PrintMyTaskList.cshtml
@model ProjectRequest.Models.TaskListInfo

@{
    Layout = null;
    
    <style type="text/css">
        table {

	        font-size:11px;
	        color:#333333;
	        border-width: 1px;
	        border-color: #666666;
	        border-collapse: collapse;
            font-size: 13px;
            font-family: 'Roboto', sans-serif;
        }
        table th {
	        border-width: 1px;
	        padding: 8px;
	        border-style: solid;
	        border-color: #666666;
	        background-color: #dedede;
        }
        table td {
	        border-width: 1px;
	        padding: 8px;
	        border-style: solid;
	        border-color: #666666;
	        background-color: #ffffff;
        }
    </style>
}

<div class='datagrid'>
<table>
<thead><tr><th>Due Date</th><th>Case Name</th><th>Task</th></thead>
<tbody>

@{
    string rowColor = "alt";
}

@foreach (var task in Model.taskView)
{
    string assignments = "";

    foreach (var staff in task.staffList)
    {
        assignments += staff + ", ";
    }

    if (rowColor == "noAlt")
    {
        rowColor = "alt";
    }
    else
    {
        rowColor = "noAlt";
    }
    
    <tr class="@rowColor" @if (task.taskList.priority == true)
                          {<text> style="outline: thin solid red"</text>}>
    <td class="hide-on-med-and-down mdl-layout--large-screen-only">@task.taskList.DueDate</td>
    @if(task.request.projectName != null)
    {
        <td >@Html.ActionLink(task.request.projectName, "ViewRequest", new { requestID = @task.request.reuqestID }, new { target = "_blank" }) </td>
    }
    else
    {
        <td >@Html.ActionLink("This case does not have a name", "ViewRequest", new { requestID = @task.request.reuqestID }, new { target = "_blank" }) </td>
    }
    <td>@task.taskList.Task</td>
@*    <td class="hide-on-med-and-down mdl-layout--large-screen-only">@assignments</td>
    <td class="hide-on-med-and-down mdl-layout--large-screen-only">@task.taskList.Status</td>*@
    @*<td class="noPrint hide-on-med-and-down mdl-layout--large-screen-only">@Html.ActionLink("Edit Case", "RequestInfo", new { requestID = @task.request.reuqestID }, new { target = "_blank" }) </td>*@
    </tr>
}

</tbody>
</table>
</div>

ProjectRequest/Views/Request/SearchCurrentTrack.cshtml
@{
    ViewBag.Title = "Search Current Track";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Search Current Track</h2>
<p>Your search did not bring up any results.</p>
<p><a href="~/Default/Index">Go back to home page.</a></p>
<p><a href="~/Request/Index">View all requests</a></p>
<p><a href="~/Assignment/Index">View assigned requests</a></p>

@using (Html.BeginForm("SearchCurrentTrack", "Request"))
{
    <p>Search Again:</p>
    <p><input type="text" name="currentTrackID" id="currentTrackID" />
    <input type="submit" name="search" value="search" /></p>
}

ProjectRequest/Views/Request/TaskList.cshtml
@model ProjectRequest.Models.TaskListInfo
@using ProjectRequest.HTMLHelpers;
@{
    ViewBag.Title = "Task Files";
    Layout = "~/Views/Shared/_LayoutCopy2017.cshtml";
    <link rel="stylesheet" href="~/css/print.css"> 
}
<script type="text/javascript">
    $(document).ready(function () {

    });
</script>


@using (Html.BeginForm((string)ViewBag.Method, "Request"))
{

<fieldset class="CaseFilter">
<legend>Filter CC Task Files</legend>


    <div class="row">

        <div class="input-field col s12 m6 l3" >
            <select name="assignedTo" id="assignedTo">
                <option value="00">Please Select:</option>
                @foreach (var staff in Model.staffList)
                {
                    if (staff.staffID == Model.PagingInfo.assignedTo)
                    {
                        <option value="@staff.staffID" selected="selected">@staff.firstName @staff.lastName</option>
                    }

                    else
                    {
                        <option value="@staff.staffID">@staff.firstName @staff.lastName</option>
                    }
                }
            </select>
            <label for="assignedTo">Assigned To:</label>
        </div>

        <div class="input-field col s12 m6 l3" >
            <select name="completed" id="completed">
                <option value="00">Please Select:</option>

                    @if (Model.PagingInfo.completed == "false")
                    {
                        <option value="true">Yes</option>
                        <option value="false" selected="selected">No</option>
                    }

                    else
                    {
                        <option value="true" selected="selected">Yes</option>
                        <option value="false">No</option>
                    }
         
            </select>
            <label for="completed">Show Completed Tasks:</label>
        </div>

       <div class="input-field col s12 m6 l3" >
            <select name="projectCompleted" id="projectCompleted">
                <option value="00">Please Select:</option>

                    @if (Model.PagingInfo.completed == "false")
                    {
                        <option value="true">Yes</option>
                        <option value="false" selected="selected">No</option>
                    }

                    else
                    {
                        <option value="true" selected="selected">Yes</option>
                        <option value="false">No</option>
                    }
         
            </select>
            <label for="projectCompleted">Show Tasks for Completed Case</label>
        </div>

        <div class="input-field col s12 m6 l3" >
            <select name="priority" id="priority">
                <option value="00">Please Select:</option>
                    @if (Model.PagingInfo.priority == "false")
                    {
                        <option value="true">Yes</option>
                        <option value="false" selected="selected">No</option>
                    }

                    else
                    {
                        <option value="true" selected="selected">Yes</option>
                        <option value="false">No</option>
                    }
         
            </select>
            <label for="priority">CC priority tasks only:</label>
        </div>

        <div class="input-field col s12 m6 l3" >
            <select name="status" id="status">
                <option value="00">Please Select:</option>
                @foreach (var status in Model.status)
                {
                    if (status.status == Model.PagingInfo.status)
                    {
                        <option value="@status.status" selected="selected">@status.status</option>      
                    }
                    else
                    {
                        <option value="@status.status" >@status.status</option>
                    }
                }
            </select>
            <label for="status">Task Status:</label>
        </div>

        <div class="input-field col s12 m6 l3" >
            <input type="text" name="dateStart" class="datepicker" id="dateStart" value="@Model.PagingInfo.dateStart" />
            <label for="dateStart">Due Date Start:</label>
        </div>

        <div class="input-field col s12 m6 l3" >
            <input type="text" name="dateEnd" class="datepicker" id="dateEnd" value="@Model.PagingInfo.dateEnd" />
            <label for="dateEnd">Due Date End:</label>
        </div>

    </div>

</fieldset>


<div class="right-align">
    <button class="btn waves-effect waves-light button" type="submit" name="action">
        Filter Task Files
        <i class="material-icons right">search</i>
    </button>
</div>

}


<fieldset class="z-depth-1">
<legend>CC Task Files - @ViewBag.TaskTotal Tasks</legend>
<br />


<table class="infoTable bordered striped centered">
<thead><tr><th class="hide-on-med-and-down">Due Date</th><th class="noPrint hide-on-med-and-down">Details</th><th>Case Name</th><th>Task</th><th class="hide-on-med-and-down">Assigned To</th><th class="hide-on-med-and-down">Status</th></thead>
<tbody>


@foreach (var task in Model.taskView)
{
    string assignments = "";

    foreach (var staff in task.staffList)
    {
        assignments += staff + ", ";
    }

    <tr>
    <td class="hide-on-med-and-down">@task.taskList.DueDate.ToString().Replace("12:00:00 AM", "")</td>

    @*Determine if the user is sent to the old edit views (single category), or the new edit veiws (multi category).*@
    @if (task.request.categoryID == "multi")
    {
        <td class="hide-on-med-and-down">
            @Html.ActionLink((task.request.reuqestID).ToString() + " (Edit)", "EditCase", new { requestID = @task.request.reuqestID }, new { target = "_blank" })
        </td>
    }
    else
    {
        <td class="hide-on-med-and-down">
            @Html.ActionLink((task.request.reuqestID).ToString() + " (Edit)", "RequestInfo", new { requestID = @task.request.reuqestID }, new { target = "_blank" })
        </td>
    }

    @*Determine if the user is sent to the old read only views (single category), or new read only veiws (multi category).*@
    @if (task.request.categoryID == "multi")
    {
        <td class="hide-on-med-and-down">
            @Html.ActionLink((task.request.projectName).ToString(), "ViewCase", new { requestID = @task.request.reuqestID }, new { target = "_blank" })
        </td>
    }
    else
    {
        <td class="hide-on-med-and-down">
            @Html.ActionLink((task.request.projectName).ToString(), "ViewRequest", new { requestID = @task.request.reuqestID }, new { target = "_blank" })
        </td>
    }

    @*@if(task.request.projectName != null)
    {
        <td >@Html.ActionLink(task.request.projectName, "ViewRequest", new { requestID = @task.request.reuqestID }, new { target = "_blank" }) </td>
    }
    else
    {
        <td >@Html.ActionLink("This case does not have a name", "ViewRequest", new { requestID = @task.request.reuqestID }, new { target = "_blank" }) </td>
    }*@

    <td>@task.taskList.Task</td>
    <td class="hide-on-med-and-down">@assignments</td>
    <td class="hide-on-med-and-down">@task.taskList.Status</td>
    </tr>
}

</tbody>

</table>

<div class="row">
    <div class="col s12">
        <p class="paging">@Html.PageLinks(Model.PagingInfo, x => Url.Action((string)ViewBag.Method, new { page = x }))</p>
     </div>
</div>

</fieldset>