ProjectRequest/Models/Calendar.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ProjectRequest.Models
{
    public class Calendar
    {
        public int requestID { get; set; }
        public string title { get; set; }
        public DateTime start { get; set; }
        public DateTime end { get; set; }
        public string category {get; set; }
        public IEnumerable<AnswerListViewModel> answerList { get; set; }
        public string assignedTo { get; set; }

    }
}

ProjectRequest/Models/TaskView.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using ProjectRequest.Models;

namespace ProjectRequest.Models
{
    public class TaskView
    {
        public TaskList taskList { get; set; }
        public List<string> staffList { get; set; }
        public Request request { get; set; }

    }
}

ProjectRequest/Controllers/CalendarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ProjectRequest.Models;

namespace ProjectRequest.Controllers
{
    public class CalendarController : Controller
    {
        //
        // GET: /Calender/

        ProjectRequestEntities request = new ProjectRequestEntities();
        
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult SchoolEvents()
        {
            return View();
        }
        public ActionResult Project()
        {
            return View();
        }

        public ActionResult Task()
        {
            return View();
        }

        public ActionResult NewSchoolEvent()
        {
            ProjectRequestEntities request = new ProjectRequestEntities();

            IEnumerable<Location> location = request.Locations.OrderByDescending(i => i.name);

            return View(location);
        }

        public JsonResult GetEvents(string start, string end)
        {
            var fromDate = Convert.ToDateTime(start);

            var toDate = Convert.ToDateTime(end);

            var eventList = request.Calenders.Where(c => c.end <= toDate && c.start >= fromDate && c.eventType == null);

            var rows = eventList.ToArray();

            return Json(rows, JsonRequestBehavior.AllowGet);

        }

        public JsonResult GetSchoolEvents(string start, string end)
        {
            var fromDate = Convert.ToDateTime(start);

            var toDate = Convert.ToDateTime(end);

            var eventList = request.Calenders.Where(c => c.end <= toDate && c.start >= fromDate && c.eventType == "School");

            var rows = eventList.ToArray();

            return Json(rows, JsonRequestBehavior.AllowGet);

        }

        public JsonResult GetProjectEvents(string start, string end, string agentAssigned)
        {
            List<Calendar> projectList = new List<Calendar>();

            var fromDate = Convert.ToDateTime(start);

            var toDate = Convert.ToDateTime(end);

            var eventList = request.Requests.Where(c => c.dueDate <= toDate && c.dueDate >= fromDate);



            foreach (var project in eventList)
            {
                var assignedTo = request.RequestAssignments.Where(t => t.requestID == project.reuqestID).ToList();

                string assignments = " - ";

                foreach (var staff in assignedTo)
                {
                    assignments += staff.staffID + ", ";
                }

                if (agentAssigned == null || assignments.Contains(agentAssigned))
                {
                    Calendar calendar = new Calendar()
                    {
                        requestID = project.reuqestID,
                        start = Convert.ToDateTime(project.dueDate),
                        end = Convert.ToDateTime(project.dueDate),
                        title = project.projectName + assignments,
                        category = project.categoryID 
                    };

                    projectList.Add(calendar);
                }

           }

            return Json(projectList, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetTaskEvents(string start, string end, string agentAssigned)
        {
            List<Calendar> projectList = new List<Calendar>();

            var fromDate = Convert.ToDateTime(start);

            var toDate = Convert.ToDateTime(end);

            var eventList = request.TaskLists.Where(c => c.DueDate <= toDate && c.DueDate >= fromDate);

            foreach (var project in eventList)
            {
                string assignments = " - ";

                //foreach (var staff in assignedTo)
                //{
                //    assignments += staff.staffID + ", ";
                //}

                var taskAssignments = request.TaskAssignments.Where(t => t.taskID == project.taskID);

                foreach (var assignment in taskAssignments)
                {
                    assignments += assignment.staffID + ", ";
                }

                if (agentAssigned == null || assignments.Contains(agentAssigned))
                {
                    Calendar calendar = new Calendar()
                    {
                        requestID = Convert.ToUInt16(project.requestID),
                        start = Convert.ToDateTime(project.DueDate),
                        end = Convert.ToDateTime(project.DueDate),
                        title = project.Task + assignments
                    };

                    projectList.Add(calendar);
                }
            }

            return Json(projectList, JsonRequestBehavior.AllowGet);
        }

        private static DateTime ConvertFromUnixTimestamp(double timestamp)
        {
            var origin = new DateTime(1970, 1, 1, 0, 0, 0, 0);

            return origin.AddSeconds(timestamp);
        }

        [AuthorizeUser]
        public ActionResult AddEvent()
        {
            string title = Request.Form["title"].ToString();
            bool delete;

            //string startDate = Request.Form["startDate"].ToString();
            DateTime StartDate = Convert.ToDateTime(Request.Form["startDate"].ToString());
            int startTime1 = Convert.ToInt16(Request.Form["startTime1"]);
            int startTime2 = Convert.ToInt16(Request.Form["startTime2"]);
            string startAmPm = Request.Form["startAmPm"].ToString();
            string startTime;

            //string endDate = Request.Form["endDate"].ToString();
            DateTime EndDate = Convert.ToDateTime(Request.Form["endDate"].ToString());
            int endTime1 = Convert.ToInt16(Request.Form["endTime1"]);
            int endTime2 = Convert.ToInt16(Request.Form["endTime2"]);
            string endAmPm = Request.Form["endAmPm"].ToString();
            string endTime;

            //bool video = Convert.ToBoolean(Request.Form["video"]);

            //string[] startDates = startDate.Split('/');
            //string[] endDates = endDate.Split('/');

            //if (startAmPm == "PM" && endTime1 < 12)
            //{
            //    endTime1 = endTime1 + 12;
            //}

            //DateTime StartDate = new DateTime(Convert.ToInt16(startDates[2]), Convert.ToInt16(startDates[0]), Convert.ToInt16(startDates[1]), startTime1, startTime2, 000);

            //if (endAmPm == "PM" && endTime1 < 12)
            //{
            //    endTime1 = endTime1 + 12;
            //}

            //DateTime EndDate = new DateTime(Convert.ToInt16(endDates[2]), Convert.ToInt16(endDates[0]), Convert.ToInt16(endDates[1]), endTime1, endTime2, 000);

            //if (EndDate > StartDate)
            //{
            //    EndDate = EndDate.AddDays(1);
            //}

            if (Request.Form["id"].ToString() == "0")
            {
                Calender calender = new Calender();

                calender.end = EndDate.AddHours(23).AddMinutes(59);
                calender.start = StartDate;
                calender.title = Request.Form["title"].ToString();
                calender.allDay = false;
                calender.location = "Creative Communications";
                //calender.allDay = Convert.ToBoolean(Request.Form["allDay"]);

                //if (video)
                //    calender.className = "videoEvent";

                request.AddToCalenders(calender);
                request.SaveChanges();
            }
            else
            {
                int eventID = Convert.ToInt16(Request.Form["id"]);

                var calender = request.Calenders.FirstOrDefault(c => c.id == eventID);

                if (Request.Form["delete"] != null)
                    delete = true;
                else
                    delete = false;

                if (delete)
                {
                    request.Calenders.DeleteObject(calender);
                }
                else
                {
                    calender.end = EndDate.AddHours(23).AddMinutes(59);
                    calender.start = StartDate;
                    calender.title = Request.Form["title"].ToString();
                    calender.allDay = false;
                    calender.location = "Creative Communications";
                    //calender.allDay = Convert.ToBoolean(Request.Form["allDay"]);


                }


                request.SaveChanges();
            }

            return RedirectToAction("Index");
        }

        [AuthorizeUser]
        public ActionResult AddSchoolEvent()
        {
            string title = Request.Form["title"].ToString();
            bool delete;

            //string startDate = Request.Form["startDate"].ToString();
            DateTime StartDate = Convert.ToDateTime(Request.Form["startDate"].ToString());

            //string endDate = Request.Form["endDate"].ToString();
            DateTime EndDate = Convert.ToDateTime(Request.Form["endDate"].ToString());

            Calender calender = new Calender();

            calender.end = EndDate.AddHours(23).AddMinutes(59);
            calender.start = StartDate;
            calender.title = Request.Form["title"].ToString();
            calender.location = Request.Form["location"].ToString();
            calender.allDay = false;
            calender.eventType = "School";
            
            request.AddToCalenders(calender);
            request.SaveChanges();

            request.SaveChanges();

            return RedirectToAction("Index");
        }
    }
}

ProjectRequest/Views/Calendar/Index.cshtml
@{
    ViewBag.Title = "Event Calender";
    Layout = "~/Views/Shared/_LayoutCopy2017.cshtml";

    <link href='~/css/fullcalendar.css' rel='stylesheet' />
    <link href='~/css/fullcalendar.print.css' rel='stylesheet' media='print' />

    <script src="https://secure.sullivan.edu/ProjectRequest/ProjectRequest/js/moment.min.js" type="text/javascript" charset="utf-8"></script>
	<script src="https://secure.sullivan.edu/ProjectRequest/ProjectRequest/js/fullcalendar.js" type="text/javascript" charset="utf-8"></script>
    <script src="https://secure.sullivan.edu/ProjectRequest/ProjectRequest/js/date.js" type="text/javascript" charset="utf-8"></script>

    <link rel="stylesheet" href="~/css/magnific-popup.css"> 

    <style type="text/css">

        .white-popup {
          position: relative;
          background: #FFF;
          padding: 20px;
          padding-top: 10px;
          padding-bottom: 10px;
          width: auto;
          max-width: 1100px;
          margin: 20px auto;
          font-size: 18px;
          font-family: 'Roboto Condensed', sans-serif;
        }

        #eventInfo
        {
            font-weight: 600;
            font-size: 18px;
        }

      body {

		font-family: 'Roboto', sans-serif;
		font-size: 14px;
	}

	#calendar {
		max-width: 1100px;
		margin: 0 auto;
        border-radius: 0.2em;
        background: white;
        box-shadow: 0px 1px 1px 0px rgba(0, 0, 0, 0.16);
        margin-top: 25px;
        padding: 10px;
	}

    h2
    {
        font-size: 25px;  
        font-family: 'Oswald', sans-serif;
        color: #2c7aff;  
    }

    .fc-toolbar
    {
        padding-top: 25px;
        padding-left: 10px;
        padding-right: 10px;
    }

    .fc-event
    {
        border: none;
        background: #2c7aff;
        padding: 2px;
        padding-left: 3px;
    }

    .fc-title, .fc-time
    {
        color: white;
        font-size: 13px;
        font-family: 'Roboto Condensed', sans-serif;
        font-weight: 600;
    }

    .fc-day-grid-event .fc-time
    {
        font-weight: 600;
    }

    .eventHeader
    {
        font-family: 'Oswald', sans-serif;
        font-size: 22px;
        color: #2F5E5E;
        font-weight: 500;
        width: 100%;
        /*margin-left: 15px;
        margin-right: 15px;*/
        border-bottom: solid 1px #708090;
        /*box-shadow: 0 2px 5px 0 rgba(0,0,0,0.16),0 2px 10px 0 rgba(0,0,0,0.12);*/
        background: white;
        padding: 10px;
        padding-bottom: 5px;
        padding-left: 0px;
        margin-bottom: 15px;
    }

    .eventHeader h5
    {
        margin: 0px;
        color: #2c7aff;
    }

    thead
    {
        border-bottom: none;
    }

    .noTopSpace
    {
        padding-top: 0px;
        margin-top: 0px;
    }

    .videoEvent,
    .videoEvent div,
    .videoEvent span {
        background-color: #2F5E5E; /* background color */
    }

    .fc-today.fc-state-highlight
    {
        background-color: #F1F3F4;
    }

    </style>
}
<script>
	$(document).ready(function() {
	    $('.time').hide();
	    $('#clearEvent').hide();
	    $('.deleteContainer').hide();


	    //$('#allDay').change(function () {
	    //    if ($('#allDay').val() == 'true') {
	    //        $('.time').hide();
	    //    }
	    //    else {
	    //        $('.time').show();
	    //    }
	    //});

		$('#calendar').fullCalendar({
			header: {
				left: 'prev,next today',
				center: 'title',
				right: 'month,basicWeek,basicDay'
			},
			eventRender: function (event, element) {
			    element.attr('href', 'javascript:void(0);');
			    element.click(function() {
			        $("#startTime").html(moment(event.start).format('MM/DD/YYYY h:mm A'));
			        $("#endTime").html(moment(event.end).format('MM/DD/YYYY h:mm A'));
			        $("#eventInfo").html(event.title);
			        $.magnificPopup.open({
			            items: {
			                src: '#eventContent'
			            },
			            type: 'inline'
			        });

			        $('#id').val(event.id);

			        $('#title').val(event.title);

			        //if (event.allDay) {
			        //    $('#allDay').val('true');
			        //    //$('.time').hide();
			        //}
			        //else {
			        //    $('#allDay').val('false');
			        //    //$('.time').show();
			        //}

			        //if (event.className == "videoEvent") {
			        //    $('#video').val('true');
			        //}
			        //else {
			        //    $('#video').val('false');
			        //}

			        var startDate = moment(event.start).format('MM/DD/YYYY hh:mm A').split(" ");
			        var startTime = startDate[1].split(':');
			        $('#startDate').val(startDate[0]);
			        $('#startTime1').val(startTime[0]);
			        $('#startTime2').val(startTime[1]);
			        $('#startAmPm').val(startDate[2]);

			        var endDate = moment(event.end).format('MM/DD/YYYY hh:mm A').split(" ");
			        $('#endDate').val(endDate[0]);

			        //if (event.allDay) {
			        //    $('#endDate').val(Date.parse(endDate[0]).addDays(-1).toString('M/d/yyyy'));
			        //}
			        //else {
			        //    $('#endDate').val(endDate[0]);
			        //}

			        var endTime = endDate[1].split(':');
			        
			        $('#endTime1').val(endTime[0]);
			        $('#endTime2').val(endTime[1]);
			        $('#endAmPm').val(endDate[2]);

			        $('#clearEvent').show();
			        $('.deleteContainer').show();
			        $('.addContent').addClass('active');
			        $('select').material_select();
			    });
			},
			editable: false,
			eventLimit: true, // allow "more" link when too many events
			events: "/ProjectRequest/ProjectRequest/Calendar/GetEvents",
			displayEventEnd: true,
		    displayEventTime: false,
            timezone: 'local'
		});
		

		$('#clearEvent').click(function () {
		    $('#id').val('0');
		    $('#title').val("");
		    $('#allDay').val('true');
		    $('.time').hide();
		    $('#startDate').val("");
		    $('#startTime1').val("00");
		    $('#startTime2').val("00");
		    $('#startAmPm').val("AM");
		    $('#endDate').val("");
		    $('#endTime1').val("00");
		    $('#endTime2').val("00");
		    $('#endAmPm').val("AM");
		    $('#clearEvent').hide();
		    $('select').material_select();
		    $('.deleteContainer').hide();
		});
	});

</script>
@using (Html.BeginForm("AddEvent", "Calendar"))
{

    <div id="eventContent" title="Event Details" class="white-popup mfp-hide">
    <div class="eventHeader">
        <h5>CC Event Info</h5>
    </div>
        Start: <span id="startTime"></span><br>
        End: <span id="endTime"></span><br>
        <p id="eventInfo"></p>
    </div>

<div class="row">
<div class="col s12">

	<div id='calendar' ></div>

</div>
</div>

<div class="row">
<div class="col s12">

<fieldset class="sectionGroup">
<legend>Add / Edit Event</legend>


    @*Track if editing an event, or adding a new one*@
    <input type="hidden" name="id" id="id" value="0" />
    
    <div class="row">

        <div class="input-field col s12" >
            <input type="text" name="title" id="title" />
            <label class="addContent">Description:</label>
        </div>

        @*<div class="input-field col s12 m2 l2" >
            <select name="allDay" id="allDay">
                <option value="true">Yes</option>
                <option value="false">No</option>
            </select>
            <label>All Day Event?</label>
        </div>*@

        @*<div class="input-field col s12 m2 l2" >
            <select name="video" id="video">
                <option value="true">Yes</option>
                <option value="false" selected>No</option>
            </select>
            <label>Video Event?</label>
        </div>*@
    
    </div>

    <div class="row">

        <div class="input-field col s12 m6 l 6" >
            <input type="text" name="startDate" id="startDate" class="datepicker" />
            <label class="addContent">Start Date:</label>
        </div>

        <div class="input-field col s12 m6 l 6" >
            <input type="text" name="endDate" id="endDate" class="datepicker" />
            <label class="addContent">End Date:</label>
        </div>
    </div>

    
   <div class="time row">
        <div class="input-field col s4 m2 l2" >
            
            <select name="startTime1" id="startTime1">
                <option value="00">00</option>
                <option value="01">01</option>
                <option value="02">02</option>
                <option value="03">03</option>
                <option value="04">04</option>
                <option value="05">05</option>
                <option value="06">06</option>
                <option value="07">07</option>
                <option value="08">08</option>
                <option value="09">09</option>
                <option value="10">10</option>
                <option value="11">11</option>
                <option value="12">12</option>
            </select>
            <label >Start Time:</label>
        </div>
        <div class="input-field col s4 m2 l2" >    
            <select name="startTime2" id="startTime2">
            @for (int i = 0; i <= 60; i++)
            {
                string time;
                if (i < 10)
                {
                    time = "0" + i.ToString();
                }
                else
                {
                    time = i.ToString();
                }

                <option value="@time">@time</option>

            } 
            </select>
        </div>
        <div class="input-field col s4 m2 l2" > 
           <select name="startAmPm">
                <option value="AM">AM</option>
                <option value="PM">PM</option>
            </select>
       </div>

        <div class="input-field col s4 m2 l2" >
            <select name="endTime1" id="endTime1">
                <option value="00">00</option>
                <option value="01">01</option>
                <option value="02">02</option>
                <option value="03">03</option>
                <option value="04">04</option>
                <option value="05">05</option>
                <option value="06">06</option>
                <option value="07">07</option>
                <option value="08">08</option>
                <option value="09">09</option>
                <option value="10">10</option>
                <option value="11">11</option>
                <option value="12">12</option>
            </select>
            <label >End Time:</label>
        </div>
        <div class="input-field col s4 m2 l2" >
            <select name="endTime2" id="endTime2">
            @for (int i = 0; i <= 60; i++)
            {
                string time;
                if (i < 10)
                {
                    time = "0" + i.ToString();
                }
                else
                {
                    time = i.ToString();
                }

                <option value="@time">@time</option>

            }   
            </select>
        </div>
        <div class="input-field col s4 m2 l2" >
            <select name="endAmPm" id="endAmPm">
                <option value="AM">AM</option>
                <option value="PM">PM</option>
            </select>
       </div>
        
    </div> @*End Time Row*@

    <div class="row extraSpace deleteContainer noTopSpace">

    <div class="input-field col s3 noTopSpace">
        <div class="switch">
        <label>
            <input type="checkbox" name="delete" id="delete" />
            <span class="lever"></span>
            Delete This Event
        </label>
        </div>
    </div>

    </div>
    <br />

</fieldset>

<div class="right-align">
    <button class="btn waves-effect waves-light button" type="submit" name="action">Save Event
        <i class="material-icons right">event</i>
    </button>
    <button class="btn waves-effect waves-light button" type="button" id="clearEvent">New Event
        <i class="material-icons right">clear</i>
    </button>
</div>
</div>
</div>
}

ProjectRequest/Views/Calendar/NewSchoolEvent.cshtml
@model IEnumerable<ProjectRequest.Models.Location>

@{
    ViewBag.Title = "New School Event";
    Layout = "~/Views/Shared/_LayoutCopy2017.cshtml";
}

<fieldset class="sectionGroup">
<legend>Add / Edit Event</legend>

    @*Track if editing an event, or adding a new one*@
    <input type="hidden" name="id" id="id" value="0" />
    
    <div class="row">

        <div class="input-field col s12" >
            <input type="text" name="title" id="title" />
            <label class="addContent">Description:</label>
        </div>
    
    </div>

    <div class="row">

        <div class="input-field col s12 m6 l6" >
            <input type="text" name="startDate" id="startDate" class="datepicker" />
            <label class="addContent">Start Date:</label>
        </div>

        <div class="input-field col s12 m6 l6" >
            <input type="text" name="endDate" id="endDate" class="datepicker" />
            <label class="addContent">End Date:</label>
        </div>
    </div>

    <div class="row">

        <div class="input-field col s12 m6 l6" >
            <select name="location" id="location">
                <option value="00">Please Select:</option>
                    @foreach (var location in Model)
                    {
                        <option value="@location.name">@location.name</option>
                    }
            </select>
            <label >Location:</label>
        </div>

    </div>

    <br />

</fieldset>

ProjectRequest/Views/Calendar/SchoolEvents.cshtml
@{
    ViewBag.Title = "School Events";
    Layout = "~/Views/Shared/_LayoutCopy2017.cshtml";

    <link href='~/css/fullcalendar.css' rel='stylesheet' />
    <link href='~/css/fullcalendar.print.css' rel='stylesheet' media='print' />

    <script src="https://secure.sullivan.edu/ProjectRequest/ProjectRequest/js/moment.min.js" type="text/javascript" charset="utf-8"></script>
    <script src="https://secure.sullivan.edu/ProjectRequest/ProjectRequest/js/fullcalendar.js" type="text/javascript" charset="utf-8"></script>
    <script src="https://secure.sullivan.edu/ProjectRequest/ProjectRequest/js/date.js" type="text/javascript" charset="utf-8"></script>

    <link rel="stylesheet" href="~/css/magnific-popup.css">

    <style type="text/css">
        .white-popup {
            position: relative;
            background: #FFF;
            padding: 20px;
            padding-top: 10px;
            padding-bottom: 10px;
            width: auto;
            max-width: 1100px;
            margin: 20px auto;
            font-size: 18px;
            font-family: 'Roboto Condensed', sans-serif;
        }

        #eventInfo {
            font-weight: 600;
            font-size: 18px;
        }

        body {
            font-family: 'Roboto', sans-serif;
            font-size: 14px;
        }

        #calendar {
            max-width: 1100px;
            margin: 0 auto;
            border-radius: 0.2em;
            background: white;
            box-shadow: 0px 1px 1px 0px rgba(0, 0, 0, 0.16);
            margin-top: 25px;
            padding: 10px;
        }

        h2 {
            font-size: 25px;
            font-family: 'Oswald', sans-serif;
            color: #2c7aff;
        }

        .fc-toolbar {
            padding-top: 25px;
            padding-left: 10px;
            padding-right: 10px;
        }

        .fc-event {
            border: none;
            background: #2c7aff;
            padding: 2px;
            padding-left: 3px;
        }

        .fc-title, .fc-time {
            color: white;
            font-size: 13px;
            font-family: 'Roboto Condensed', sans-serif;
            font-weight: 600;
        }

        .fc-day-grid-event .fc-time {
            font-weight: 600;
        }

        .eventHeader {
            font-family: 'Oswald', sans-serif;
            font-size: 22px;
            color: #2F5E5E;
            font-weight: 500;
            width: 100%;
            /*margin-left: 15px;
        margin-right: 15px;*/
            border-bottom: solid 1px #708090;
            /*box-shadow: 0 2px 5px 0 rgba(0,0,0,0.16),0 2px 10px 0 rgba(0,0,0,0.12);*/
            background: white;
            padding: 10px;
            padding-bottom: 5px;
            padding-left: 0px;
            margin-bottom: 15px;
        }

            .eventHeader h5 {
                margin: 0px;
                color: #2c7aff;
            }

        thead {
            border-bottom: none;
        }

        .noTopSpace {
            padding-top: 0px;
            margin-top: 0px;
        }

        .videoEvent,
        .videoEvent div,
        .videoEvent span {
            background-color: #2F5E5E; /* background color */
        }

        .fc-today.fc-state-highlight {
            background-color: #F1F3F4;
        }
    </style>
}
<script>
	$(document).ready(function() {
	    $('.time').hide();
	    $('#clearEvent').hide();
	    $('.deleteContainer').hide();


	    //$('#allDay').change(function () {
	    //    if ($('#allDay').val() == 'true') {
	    //        $('.time').hide();
	    //    }
	    //    else {
	    //        $('.time').show();
	    //    }
	    //});

		$('#calendar').fullCalendar({
			header: {
				left: 'prev,next today',
				center: 'title',
				right: 'month,basicWeek,basicDay'
			},
			eventRender: function (event, element) {
			    element.attr('href', 'javascript:void(0);');
			    element.click(function() {
			        $("#startTime").html(moment(event.start).format('MM/DD/YYYY h:mm A'));
			        $("#endTime").html(moment(event.end).format('MM/DD/YYYY h:mm A'));
			        $("#eventInfo").html(event.title);
			        $.magnificPopup.open({
			            items: {
			                src: '#eventContent'
			            },
			            type: 'inline'
			        });

			        $('#id').val(event.id);

			        $('#title').val(event.title);

			        //if (event.allDay) {
			        //    $('#allDay').val('true');
			        //    //$('.time').hide();
			        //}
			        //else {
			        //    $('#allDay').val('false');
			        //    //$('.time').show();
			        //}

			        //if (event.className == "videoEvent") {
			        //    $('#video').val('true');
			        //}
			        //else {
			        //    $('#video').val('false');
			        //}

			        var startDate = moment(event.start).format('MM/DD/YYYY hh:mm A').split(" ");
			        var startTime = startDate[1].split(':');
			        $('#startDate').val(startDate[0]);
			        $('#startTime1').val(startTime[0]);
			        $('#startTime2').val(startTime[1]);
			        $('#startAmPm').val(startDate[2]);

			        var endDate = moment(event.end).format('MM/DD/YYYY hh:mm A').split(" ");
			        $('#endDate').val(endDate[0]);

			        //if (event.allDay) {
			        //    $('#endDate').val(Date.parse(endDate[0]).addDays(-1).toString('M/d/yyyy'));
			        //}
			        //else {
			        //    $('#endDate').val(endDate[0]);
			        //}

			        var endTime = endDate[1].split(':');

			        $('#endTime1').val(endTime[0]);
			        $('#endTime2').val(endTime[1]);
			        $('#endAmPm').val(endDate[2]);

			        $('#clearEvent').show();
			        $('.deleteContainer').show();
			        $('.addContent').addClass('active');
			        $('select').material_select();
			    });
			},
			editable: false,
			eventLimit: true, // allow "more" link when too many events
			events: "/ProjectRequest/ProjectRequest/Calendar/GetEvents",
			displayEventEnd: true,
		    displayEventTime: false,
            timezone: 'local'
		});


		$('#clearEvent').click(function () {
		    $('#id').val('0');
		    $('#title').val("");
		    $('#allDay').val('true');
		    $('.time').hide();
		    $('#startDate').val("");
		    $('#startTime1').val("00");
		    $('#startTime2').val("00");
		    $('#startAmPm').val("AM");
		    $('#endDate').val("");
		    $('#endTime1').val("00");
		    $('#endTime2').val("00");
		    $('#endAmPm').val("AM");
		    $('#clearEvent').hide();
		    $('select').material_select();
		    $('.deleteContainer').hide();
		});
	});

</script>
@using (Html.BeginForm("AddEvent", "Calendar"))
{

    <div id="eventContent" title="Event Details" class="white-popup mfp-hide">
        <div class="eventHeader">
            <h5>CC Event Info</h5>
        </div>
        Start: <span id="startTime"></span><br>
        End: <span id="endTime"></span><br>
        <p id="eventInfo"></p>
    </div>

    <div class="row">
        <div class="col s12">
            <div id='calendar'></div>
        </div>
    </div>


}